import { StyleSheet } from 'react-native';
import { darkTheme, lightTheme } from '../context/ThemeContext'; // Sesuaikan path

export const getStyles = (isDarkMode: boolean) => {
  const THEME = isDarkMode ? darkTheme : lightTheme;

  return StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: THEME.BG,
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 20,
      paddingVertical: 15,
      borderBottomWidth: 1,
      borderBottomColor: THEME.BORDER,
    },
    backBtn: {
      width: 40,
      height: 40,
      borderRadius: 12,
      backgroundColor: THEME.INPUT_BG,
      justifyContent: 'center',
      alignItems: 'center',
    },
    headerTitle: {
      fontSize: 18,
      fontWeight: '800',
      color: THEME.TEXT_MAIN,
    },
    container: {
      padding: 24,
    },
    sectionLabel: {
      fontSize: 22,
      fontWeight: '900',
      color: THEME.TEXT_MAIN,
      marginBottom: 25,
      letterSpacing: -0.5,
    },
    inputContainer: {
      marginBottom: 24,
    },
    label: {
      fontSize: 12,
      fontWeight: '800',
      color: THEME.TEXT_SUB,
      textTransform: 'uppercase',
      letterSpacing: 1,
      marginBottom: 10,
    },
    input: {
      backgroundColor: THEME.INPUT_BG,
      borderWidth: 1,
      borderColor: THEME.BORDER,
      borderRadius: 16,
      paddingHorizontal: 16,
      paddingVertical: 14,
      fontSize: 15,
      color: THEME.TEXT_MAIN,
      fontWeight: '600',
    },
    textArea: {
      height: 120,
      paddingTop: 16,
    },
    sportRow: {
      flexDirection: 'row',
      gap: 12,
    },
    sportBtn: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      paddingVertical: 14,
      backgroundColor: THEME.INPUT_BG,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: THEME.BORDER,
    },
    activeSportBtn: {
      backgroundColor: THEME.ACCENT,
      borderColor: THEME.ACCENT,
      shadowColor: THEME.ACCENT,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 8,
      elevation: 4,
    },
    sportBtnText: {
      fontSize: 14,
      fontWeight: '700',
      color: THEME.TEXT_SUB,
    },
    activeSportBtnText: {
      color: '#FFFFFF',
    },
    saveBtn: {
      backgroundColor: THEME.ACCENT,
      flexDirection: 'row',
      height: 58,
      borderRadius: 18,
      justifyContent: 'center',
      alignItems: 'center',
      gap: 12,
      marginTop: 10,
      shadowColor: THEME.ACCENT,
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: isDarkMode ? 0.3 : 0.1,
      shadowRadius: 20,
      elevation: 8,
    },
    disabledBtn: {
      opacity: 0.7,
    },
    saveBtnText: {
      color: '#FFFFFF',
      fontSize: 16,
      fontWeight: '800',
      letterSpacing: 0.5,
    },

    // --- MODAL STYLES (Dipindahkan ke sini agar dinamis) ---
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.6)',
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
    },
    modalCard: {
      width: '100%',
      backgroundColor: THEME.CARD,
      borderRadius: 24,
      padding: 24,
      alignItems: 'center',
      borderWidth: isDarkMode ? 1 : 0,
      borderColor: THEME.BORDER,
      elevation: 10,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 12,
    },
    modalTitle: {
      fontSize: 22,
      fontWeight: 'bold',
      color: THEME.TEXT_MAIN,
      marginBottom: 8,
    },
    confirmText: {
      fontSize: 14,
      color: THEME.TEXT_SUB,
      textAlign: 'center',
      marginBottom: 24,
    },
    modalButtons: {
      flexDirection: 'row',
      gap: 12,
      width: '100%',
    },
    modalBtnDiscard: {
      flex: 1,
      height: 48,
      borderRadius: 14,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: isDarkMode ? '#2A1212' : '#FEE2E2', // Merah pucat/gelap
      borderWidth: 1,
      borderColor: isDarkMode ? '#8B0000' : '#FECACA',
    },
    modalBtnSave: {
      flex: 1,
      height: 48,
      borderRadius: 14,
      backgroundColor: THEME.ACCENT,
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: THEME.ACCENT,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 4,
    },
  });
};